### ISSUE TITLE
Changing name to RC_receiver broke the examples

### ISSUE THREAD

**Issue by zlite** [Nilon123456789/Receiver#1]
The examples are still looking for receiver.h, not RC_receiver,h

**Comment by Nilon123456789** [comment]
Patched in the [v1.0.1](https://github.com/Nilon123456789/Receiver/tree/v1.0.1)

**Comment by zlite** [comment]
Sadly examples still don't compile:

\RC_raw\RC_raw.ino:14:1: error: 'Receiver' does not name a type; did you mean 'RC_Receiver'?
 Receiver receiver(2,3,4,5);

**Comment by Nilon123456789** [comment]
Should now be fixed in version v1.0.2
